// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjE8Ugj3rKXWzMTTVthMRyiMkNRk6slPI',
    appId: '1:964129578811:web:7c3f883190542faa31611e',
    messagingSenderId: '964129578811',
    projectId: 'thalassa-hotel-relation-guest',
    authDomain: 'thalassa-hotel-relation-guest.firebaseapp.com',
    storageBucket: 'thalassa-hotel-relation-guest.firebasestorage.app',
    measurementId: 'G-6R8V4NH23Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBitAss0pZNAxQ8c92HLIaqwFbCcSYcats',
    appId: '1:964129578811:android:ed676ab1de7f5f4f31611e',
    messagingSenderId: '964129578811',
    projectId: 'thalassa-hotel-relation-guest',
    storageBucket: 'thalassa-hotel-relation-guest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXx-3rRmgIAHJtdxvqNy3ci-dOYuvcTZo',
    appId: '1:964129578811:ios:d82bdf6d77810a4131611e',
    messagingSenderId: '964129578811',
    projectId: 'thalassa-hotel-relation-guest',
    storageBucket: 'thalassa-hotel-relation-guest.firebasestorage.app',
    iosBundleId: 'com.example.thalassaContact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXx-3rRmgIAHJtdxvqNy3ci-dOYuvcTZo',
    appId: '1:964129578811:ios:d82bdf6d77810a4131611e',
    messagingSenderId: '964129578811',
    projectId: 'thalassa-hotel-relation-guest',
    storageBucket: 'thalassa-hotel-relation-guest.firebasestorage.app',
    iosBundleId: 'com.example.thalassaContact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjE8Ugj3rKXWzMTTVthMRyiMkNRk6slPI',
    appId: '1:964129578811:web:6bc5428df3dbff1f31611e',
    messagingSenderId: '964129578811',
    projectId: 'thalassa-hotel-relation-guest',
    authDomain: 'thalassa-hotel-relation-guest.firebaseapp.com',
    storageBucket: 'thalassa-hotel-relation-guest.firebasestorage.app',
    measurementId: 'G-PSDK2HHE8T',
  );
}
